sonar.projectKey=Bushko6_shopping-list
sonar.organization=Bushko6
sonar.projectName=shopping-list
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,docs/**,public/**
sonar.host.url=https://sonarcloud.io
